
# 1번
CREATE TABLE BOOK_INFO(
	BOOK_NUM INT PRIMARY KEY
	,BOOK_NAME VARCHAR(10) NOT NULL
	,WRITER VARCHAR(10) NOT NULL
	,BOOK_PRICE INT 
	,BOOK_CP VARCHAR(15) DEFAULT '미지정'
	,BOOK_DATE DATETIME
	
	
);
# 2번
INSERT INTO BOOK_INFO (BOOK_NUM,BOOK_NAME,WRITER,BOOK_PRICE,BOOK_CP,BOOK_DATE) 
 VALUES(101,'자바기초','홍길동',30000,'A출판','2025-02-15');


INSERT INTO BOOK_INFO (BOOK_NUM,BOOK_NAME,WRITER,BOOK_PRICE,BOOK_CP,BOOK_DATE) 
 VALUES(102,'리액트기초','이순신',20000,'B출판','2025-01-22');


# 3번
UPDATE BOOK_INFO SET BOOK_NAME = '자바_고급',BOOK_PRICE = 25000,BOOK_CP = 'IT출판'
 WHERE BOOK_NUM = 101;


# 4번 
SELECT EMPNO,ENAME,SAL,COMM AS '인센티브' FROM emp WHERE SAL BETWEEN 500 AND 3000
AND COMM IS NOT NULL;

# 5번
SELECT EMPNO,ENAME,JOB,HIREDATE FROM emp WHERE ENAME LIKE '%병%'OR ENAME LIKE'%김%'
ORDER BY EMPNO DESC;

# 6번
SELECT EMPNO,ENAME,DEPTNO,
CASE WHEN DEPTNO = 10 THEN '인사부'
WHEN DEPTNO = 20 THEN '영업부'
WHEN DEPTNO = 30 THEN '개발부'
ELSE '생산부'
END AS '부서명'
 FROM emp; 

#7번
SELECT EMPNO,ENAME,HIREDATE,IFNULL(COMM,0) FROM emp
WHERE  TO_CHAR(HIREDATE,'MM') % 2 =0
ORDER BY HIREDATE ASC;


#8번 
SELECT EMPNO,ENAME,HIREDATE,SAL, E.DEPTNO FROM emp E
INNER JOIN dept D
ON D.DEPTNO = E.DEPTNO
WHERE DNAME != '인사부' AND SAL >= 500 ORDER BY EMPNO DESC ,ENAME ASC;

#9번
SELECT EMPNO,DEPTNO,DNAME, ENAME AS 이름,HIRDATE FROM emp A INNER JOIN dept B
ON A.DEPTNO = B.DEPTNO


#10번 


