SELECT * FROM study_student;

SELECT STU_NUM AS 학생번호 , STU_NAME AS 학생명 , KOR_SCORE, ENG_SCORE FROM study_student 
WHERE KOR_SCORE >= 60 AND ENG_SCORE >= 70 ;


SELECT * FROM  study_student WHERE CLASS_NAME IN 
('디자인반','영상반') AND HOBBY IS NOT NULL;

SELECT STU_NUM, STU_NAME, KOR_SCORE FROM study_student WHERE
STU_NAME LIKE ('김%') AND
 KOR_SCORE BETWEEN 70 AND 85 
 ORDER BY  STU_NUM DESC;
 
 SELECT STU_NUM, STU_NAME,CLASS_NAME,ENG_SCORE FROM study_student WHERE
 HOBYY IS NOT NULL   ORDER BY CLASS_NAME ASC 
 ,  ENG_SCORE  DESC;

SELECT * FROM study_student WHERE
KOR_SCORE + ENG_SCORE >= 170;

SELECT STU_NUM, STU_NAME,KOR_SCORE,ENG_SCORE , KOR_SCORE+ENG_SCORE
FROM study_student WHERE
CLASS_NAME != '영상반';


SELECT DISTINCT HOBBY FROM study_student;





















