# 1번
CREATE TABLE MY_MEMBER(
NUM INT PRIMARY KEY,
ID VARCHAR(10) NOT NULL,
PW VARCHAR(20) NOT NULL,
NAME VARCHAR(15) NOT NULL,
AGE INT DEFAULT 0,
EMAIL VARCHAR(20) UNIQUE
);


# 2번
INSERT INTO my_member (NUM ,ID,PW,NAME,AGE,EMAIL)
 VALUES(101,'KIM','1234','김자바',30,'KIM@gmail');

INSERT INTO my_member (NUM ,ID,PW,NAME,AGE,EMAIL)
 VALUES(102,'HONG','5678','홍자바',25,'HONG@gmail');

SELECT * FROM my_member;

#3번
UPDATE my_member SET NAME = '유관순',AGE = 35 WHERE NUM =101;

#4번
SELECT EMPNO,ENAME,SAL,COMM FROM emp WHERE SAL BETWEEN 500 AND 3000
AND COMM IS NOT NULL;

#5번 
SELECT EMPNO,ENAME,HIREDATE FROM emp WHERE ENAME LIKE '%기'OR ENAME LIKE'%김%'
ORDER BY EMPNO DESC;



#6번 예시

SELECT EMPNO,ENAME,DEPTNO,
CASE WHEN DEPTNO = 10 THEN '인사부'
WHEN DEPTNO = 20 THEN '영업부'
WHEN DEPTNO = 30 THEN '개발부'
ELSE '생산부'
END AS '부서명'
 FROM emp; 




SELECT * FROM emp;

SELECT SAL,
CASE WHEN SAL >500 THEN '500이상' 
WHEN SAL < 500 THEN '500미만' 
ELSE '500'
END AS AAA
FROM emp ;





# 7번 
SELECT EMPNO,ENAME,HIREDATE,IFNULL(COMM,0) FROM emp
WHERE MONTH(HIREDATE)=1 
ORDER BY HIREDATE ASC;




#10번
SELECT EMPNO,ENAME,HIREDATE,SAL,E.DEPTNO,D.DEPTNO,DNAME FROM emp E INNER JOIN dept D
ON E.DEPTNO =D.DEPTNO WHERE DNAME != '인사부' AND SAL >= 500
ORDER BY EMPNO DESC, ENAME ASC;




