 # 도서 쇼핑몰 프로젝트 테이블
 
 # 도서 카테고리 테이블(소설, 자기계발, IT서적...)
 CREATE TABLE BOOK_CATEGORY (
 	CATE_CODE INT PRIMARY KEY AUTO_INCREMENT 	#카테고리 코드
 	, CATE_NAME VARCHAR(30) NOT NULL UNIQUE	#카테고리 이름
 );
 
INSERT INTO book_category VALUES(1,'IT/인터넷');
INSERT INTO book_category VALUES(2,'소설');
INSERT INTO book_category VALUES(3,'자기계발');
 
 COMMIT;
 SELECT * FROM book_category;
 
 #도서 테이블
 CREATE TABLE BOOK (
 	BOOK_CODE INT PRIMARY KEY AUTO_INCREMENT	
 	, BOOK_NAME VARCHAR(30) NOT NULL
 	, BOOK_PRICE INT NOT NULL
 	, PUBLISHER VARCHAR(30) NOT NULL # 출판사
 	, BOOK_INFO VARCHAR(100)
 	, REG_DATE DATETIME DEFAULT SYSDATE()
 	, BOOK_STOCK INT DEFAULT 10 # 재고 
	, CATE_CODE INT NOT NULL REFERENCES BOOK_CATEGORY (CATE_CODE) 
 );
 
 
  CREATE TABLE SHOP_USER (
 	USER_ID VARCHAR(30) PRIMARY KEY
 	,USER_PW VARCHAR(30) NOT NULL
 	,USER_NAME VARCHAR(10) NOT NULL
 	,USER_EMAIL VARCHAR(30) 
 	,USER_TEL VARCHAR(16) NOT NULL UNIQUE
 	,USER_ROLL VARCHAR(10) DEFAULT 'USER'
 	,IS_USING VARCHAR(10) DEFAULT 'Y'
 	,JOIN_DATA DATETIME DEFAULT SYSDATE()
 	
 );
 
 
SELECT * FROM SHOP_USER;
 
 
 SELECT  *
 FROM SHOP_USER
 WHERE USER_ID = '111'
 AND USER_PW = '111';
 

 SELECT * FROM book;
 
 SELECT B.CATE_CODE,BOOK_NAME,BOOK_PRICE,PUBLISHER,BOOK_INFO,REG_DATE,BOOK_STOCK
FROM BOOK B INNER JOIN BOOK_CATEGORY R
ON B.CATE_CODE = R.CATE_CODE;
 
 SELECT  CATE_NAME 
 FROM book_category
 WHERE CATE_NAME= '에세이';
 
 