

# 회원 한명의 이름과 나이를 변경하는 기능 
UPDATE rest_member SET MEM_NAME = 'TTTT', MEM_AGE = 35 WHERE MEM_ID = 'AAA';



# 회원 정보 테이블 
CREATE TABLE REST_member(
	MEM_ID VARCHAR(10) PRIMARY KEY,
	MEM_NAME VARCHAR(10) NOT NULL,
	MEM_AGE INT DEFAULT 0,
	MEM_TEL VARCHAR(15) UNIQUE

);


SELECT * FROM REST_member;

INSERT INTO REST_MEMBER  VALUES ('AAA','KIM',20,'010-1111-1111');
INSERT INTO REST_MEMBER  VALUES ('BB','LEE',30,'010-2222-1111');
INSERT INTO REST_MEMBER  VALUES ('CC','HONG',40,'010-3333-1111');

COMMIT;


# 회원 한명의 모든 컬럼 정보를 조회 
SELECT * FROM rest_member WHERE MEM_ID = 'CC';


SELECT * FROM rest_member WHERE MEM_ID = 'AAA' AND MEM_AGE = 20;

# 회원정보 등록 
INSERT INTO rest_member(MEM_ID, MEM_NAME,MEM_AGE ,MEM_TEL) 
VALUES ('DDD','PARK',50,'010');


# 게시글 정보 테이블


CREATE TABLE REST_BOARD(
	BOARD_NUM INT PRIMARY KEY,
	TITLE VARCHAR(10) NOT NULL,
	CONTENT VARCHAR(20),
	WRITER VARCHAR(10)

);

INSERT INTO REST_BOARD VALUES(1,'제목1','내용1','KIM');
INSERT INTO REST_BOARD VALUES(2,'제목2','내용2','KIM');
INSERT INTO REST_BOARD VALUES(3,'제목3','내용3','KIM');

COMMIT;

SELECT * FROM rest_board;

# CRUD 기능을 할수있는 RESTfuLL API 구현.


# 상품정보 테이블 
CREATE TABLE REST_ITEM (
	ITEM_CODE INT PRIMARY KEY AUTO_INCREMENT,
	ITEM_NAME VARCHAR(20) NOT NULL,
	ITEM_PRICE INT,
	ITEM_COLOR VARCHAR(10)

);

INSERT INTO rest_item (ITEM_NAME,ITEM_PRICE,ITEM_COLOR) VALUES('청바지',30000,'파란색');

SELECT * FROM rest_item;


ROLLBACK;











